name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Lint addon
        uses: kewisch/action-web-ext@v1
        with:
          cmd: lint
          source: addon
          channel: listed
      - name: Build addon
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: addon
          filename: "{name}-{version}.xpi"
          ignoreFiles: '["web-ext-artifacts","node_modules","*.md"]'
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: target.xpi
          path: ${{ steps.web-ext-build.outputs.target }}
